# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prep:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install && npm install firebase-tools && ./node_modules/.bin/bower install

      - save_cache:
          paths:
            - node_modules
            - bower_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - ./*
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist/*

  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm test

  deploy_to_prod:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - deploy:
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project=$FIREBASE_PROJECT_PROD

  deploy_to_test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - deploy:
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN_TEST --project=$FIREBASE_PROJECT_TEST

workflows:
  version: 2
  deploy_develop:
    jobs:
      - prep:
          filters:
            branches:
              only:
                - develop
      - build:
          requires:
            - prep
      - deploy_to_prod:
          requires:
            - build
  deploy_release:
    jobs:
      - prep:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^\d.\d.\d$/
      - build:
          requires:
            - prep
      - deploy_to_prod:
          requires:
            - build

#  deploy_release:
#    jobs:
#      - build_old:
#          filters:
#            branches:
#              only:
#                - master
#                - develop
