# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prep:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install && npm install firebase-tools && ./node_modules/.bin/bower install

      - save_cache:
          paths:
            - node_modules
            - bower_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./*
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: npm run build

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/*

  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: npm test

  deploy_to_prod:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace/dist

      - deploy:
        name: Deploy to Firebase Production
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

  build_old:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install && npm install firebase-tools && ./node_modules/.bin/bower install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run build

      - deploy:
         name: Deploy Master to Firebase
         command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
          fi
workflows:
  version: 2
  modular:
    jobs:
      - prep
      - build:
          requires:
            - prep
#      - deploy_to_prod:
#          requires:
#            - build

#  deploy_release:
#    jobs:
#      - build_old:
#          filters:
#            branches:
#              only:
#                - master
#                - develop
